In [ ]:
#Data Import and Cleaning

In [2]:
#Data Source - Kaggle - https://www.kaggle.com/datasets/rohanrao/nifty50-stock-market-data
import pandas as pd
import matplotlib.pyplot as plt 
from statsmodels.tsa.arima_model import ARMA
TempData = pd.read_csv('HCLTECH.csv')
TempData.head(30)

,Date,Symbol,Series,Prev Close,Open,High,Low,Last,Close,VWAP,Volume,Turnover,Trades,Deliverable Volume,%Deliverble
0,2000-01-11,HCLTECH,EQ,580.00,1550.00,1725.00,1492.00,1560.00,1554.45,1582.72,1192200,1.886915e+14,NaN,NaN,NaN
1,2000-01-12,HCLTECH,EQ,1554.45,1560.00,1678.85,1560.00,1678.85,1678.85,1657.05,344850,5.714349e+13,NaN,NaN,NaN
2,2000-01-13,HCLTECH,EQ,1678.85,1790.00,1813.20,1781.00,1813.20,1813.20,1804.69,53000,9.564880e+12,NaN,NaN,NaN
3,2000-01-14,HCLTECH,EQ,1813.20,1958.30,1958.30,1835.00,1958.30,1958.30,1939.90,270950,5.256169e+13,NaN,NaN,NaN
4,2000-01-17,HCLTECH,EQ,1958.30,2115.00,2115.00,1801.65,1801.65,1801.65,1990.55,428800,8.535473e+13,NaN,NaN,NaN
5,2000-01-18,HCLTECH,EQ,1801.65,1730.55,1815.00,1657.55,1775.00,1774.50,1716.39,359900,6.177280e+13,NaN,NaN,NaN
6,2000-01-19,HCLTECH,EQ,1774.50,1815.00,1889.00,1760.00,1842.80,1851.15,1842.81,316050,5.824204e+13,NaN,NaN,NaN
7,2000-01-20,HCLTECH,EQ,1851.15,1865.00,1865.00,1750.00,1753.50,1757.85,1801.37,204700,3.687409e+13,NaN,NaN,NaN
8,2000-01-21,HCLTECH,EQ,1757.85,1761.00,1815.00,1705.00,1786.00,1781.35,1774.01,282150,5.005360e+13,NaN,NaN,NaN
9,2000-01-24,HCLTECH,EQ,1781.35,1834.90,1923.90,1795.00,1923.90,1923.90,1875.34,328650,6.163317e+13,NaN,NaN,NaN
10,2000-01-25,HCLTECH,EQ,1923.90,1990.00,2077.85,1990.00,2077.85,2077.85,2065.71,313500,6.476010e+13,NaN,NaN,NaN
11,2000-01-27,HCLTECH,EQ,2077.85,2239.90,2239.90,1965.00,2078.00,2080.60,2101.92,352400,7.407150e+13,NaN,NaN,NaN
12,2000-01-28,HCLTECH,EQ,2080.60,2100.00,2245.00,2020.20,2190.00,2196.95,2173.00,360800,7.840197e+13,NaN,NaN,NaN
13,2000-01-31,HCLTECH,EQ,2196.95,2111.00,2200.00,2021.20,2021.20,2030.40,2083.45,217650,4.534620e+13,NaN,NaN,NaN
14,2000-02-01,HCLTECH,EQ,2030.40,1981.20,2180.00,1981.20,2160.00,2162.25,2110.66,261000,5.508834e+13,NaN,NaN,NaN
15,2000-02-02,HCLTECH,EQ,2162.25,2260.00,2260.00,2010.00,2035.00,2024.25,2085.91,326550,6.811542e+13,NaN,NaN,NaN
16,2000-02-03,HCLTECH,EQ,2024.25,2075.00,2075.00,1915.20,1965.00,1956.50,1989.66,175800,3.497821e+13,NaN,NaN,NaN
17,2000-02-04,HCLTECH,EQ,1956.50,1993.00,2064.00,1965.00,1977.00,1986.60,2008.25,176500,3.544560e+13,NaN,NaN,NaN
18,2000-02-07,HCLTECH,EQ,1986.60,1985.00,2119.95,1960.05,2036.00,2062.95,2048.51,277850,5.691791e+13,NaN,NaN,NaN
19,2000-02-08,HCLTECH,EQ,2062.95,2049.40,2060.00,1970.00,2014.00,1999.20,2017.09,199100,4.016027e+13,NaN,NaN,NaN
20,2000-02-09,HCLTECH,EQ,1999.20,2100.00,2100.00,1975.00,1991.00,1999.00,2011.50,180500,3.630763e+13,NaN,NaN,NaN
21,2000-02-10,HCLTECH,EQ,1999.00,1976.65,2014.80,1965.00,1990.00,1996.75,1992.36,76850,1.531132e+13,NaN,NaN,NaN
22,2000-02-11,HCLTECH,EQ,1996.75,1998.00,2156.50,1992.00,2156.50,2156.50,2110.61,166150,3.506781e+13,NaN,NaN,NaN
23,2000-02-14,HCLTECH,EQ,2156.50,2199.00,2329.05,2199.00,2329.05,2324.70,2293.27,265150,6.080618e+13,NaN,NaN,NaN
24,2000-02-15,HCLTECH,EQ,2324.70,2350.00,2510.70,2210.00,2500.00,2508.40,2425.21,224500,5.444586e+13,NaN,NaN,NaN
25,2000-02-16,HCLTECH,EQ,2508.40,2560.00,2560.00,2307.75,2418.00,2423.10,2411.48,260850,6.290343e+13,NaN,NaN,NaN
26,2000-02-17,HCLTECH,EQ,2423.10,2445.00,2616.95,2380.00,2616.95,2614.70,2526.71,276550,6.987609e+13,NaN,NaN,NaN
27,2000-02-18,HCLTECH,EQ,2614.70,2800.00,2823.90,2760.50,2771.00,2775.95,2807.40,173400,4.868032e+13,NaN,NaN,NaN
28,2000-02-21,HCLTECH,EQ,2775.95,2823.00,2998.00,2725.00,2805.00,2819.15,2883.95,151800,4.377830e+13,NaN,NaN,NaN
29,2000-02-22,HCLTECH,EQ,2819.15,2800.00,2875.00,2652.00,2710.00,2700.30,2772.79,88250,2.446984e+13,NaN,NaN,NaN